CREATE TABLE IF NOT EXISTS productos (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
	codigo VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS existencias (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	referencia VARCHAR(100),
	cantidad DECIMAL(19, 2)
);

CREATE TABLE IF NOT EXISTS proveedores (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
	nif VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ordenes_compra (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	numero VARCHAR(50) NOT NULL,
	estado VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS almacenes (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
	ubicacion VARCHAR(255)
);
